/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jhona
 */
public class Janela extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Janela.class.getName());

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
        setSize(400, 255);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgContas = new javax.swing.ButtonGroup();
        jlAgencia = new javax.swing.JLabel();
        jtfAgencia = new javax.swing.JTextField();
        jlConta = new javax.swing.JLabel();
        jtfConta = new javax.swing.JTextField();
        jSeparator01 = new javax.swing.JSeparator();
        jlNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jlEndereco = new javax.swing.JLabel();
        jtfEndereco = new javax.swing.JTextField();
        jlTelefone = new javax.swing.JLabel();
        jtfTelefone = new javax.swing.JTextField();
        jlCpf = new javax.swing.JLabel();
        jtfCpf = new javax.swing.JTextField();
        jrbCorrente = new javax.swing.JRadioButton();
        jrbPoupanca = new javax.swing.JRadioButton();
        jSeparator02 = new javax.swing.JSeparator();
        jbConsultar = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laboratório de Programação");
        setPreferredSize(new java.awt.Dimension(400, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        jlAgencia.setText("Código da Agência:");
        jlAgencia.setPreferredSize(new java.awt.Dimension(110, 18));
        getContentPane().add(jlAgencia);
        jlAgencia.setBounds(10, 10, 110, 18);
        getContentPane().add(jtfAgencia);
        jtfAgencia.setBounds(125, 10, 50, 20);

        jlConta.setText("Número da Conta:");
        getContentPane().add(jlConta);
        jlConta.setBounds(205, 10, 105, 18);
        getContentPane().add(jtfConta);
        jtfConta.setBounds(315, 10, 60, 20);
        getContentPane().add(jSeparator01);
        jSeparator01.setBounds(10, 40, 365, 10);

        jlNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlNome.setText("Nome:");
        getContentPane().add(jlNome);
        jlNome.setBounds(10, 50, 60, 18);
        getContentPane().add(jtfNome);
        jtfNome.setBounds(75, 50, 300, 20);

        jlEndereco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlEndereco.setText("Endereço:");
        getContentPane().add(jlEndereco);
        jlEndereco.setBounds(10, 75, 60, 18);
        getContentPane().add(jtfEndereco);
        jtfEndereco.setBounds(75, 75, 300, 20);

        jlTelefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlTelefone.setText("Telefone:");
        getContentPane().add(jlTelefone);
        jlTelefone.setBounds(10, 100, 60, 18);
        getContentPane().add(jtfTelefone);
        jtfTelefone.setBounds(75, 100, 300, 20);

        jlCpf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlCpf.setText("CPF:");
        getContentPane().add(jlCpf);
        jlCpf.setBounds(10, 125, 60, 18);
        getContentPane().add(jtfCpf);
        jtfCpf.setBounds(75, 125, 300, 20);

        bgContas.add(jrbCorrente);
        jrbCorrente.setMnemonic('C');
        jrbCorrente.setSelected(true);
        jrbCorrente.setText("Conta Corrente");
        getContentPane().add(jrbCorrente);
        jrbCorrente.setBounds(100, 150, 111, 20);

        bgContas.add(jrbPoupanca);
        jrbPoupanca.setMnemonic('P');
        jrbPoupanca.setText("Conta Poupança");
        getContentPane().add(jrbPoupanca);
        jrbPoupanca.setBounds(225, 150, 118, 20);
        getContentPane().add(jSeparator02);
        jSeparator02.setBounds(10, 180, 365, 10);

        jbConsultar.setMnemonic('S');
        jbConsultar.setText("Consultar");
        getContentPane().add(jbConsultar);
        jbConsultar.setBounds(35, 190, 100, 23);

        jbAtualizar.setMnemonic('A');
        jbAtualizar.setText("Atualizar");
        jbAtualizar.setEnabled(false);
        getContentPane().add(jbAtualizar);
        jbAtualizar.setBounds(145, 190, 100, 23);

        jbFechar.setMnemonic('F');
        jbFechar.setText("Fechar");
        jbFechar.addActionListener(this::jbFecharActionPerformed);
        getContentPane().add(jbFechar);
        jbFechar.setBounds(255, 190, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Janela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgContas;
    private javax.swing.JSeparator jSeparator01;
    private javax.swing.JSeparator jSeparator02;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbConsultar;
    private javax.swing.JButton jbFechar;
    private javax.swing.JLabel jlAgencia;
    private javax.swing.JLabel jlConta;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JRadioButton jrbCorrente;
    private javax.swing.JRadioButton jrbPoupanca;
    private javax.swing.JTextField jtfAgencia;
    private javax.swing.JTextField jtfConta;
    private javax.swing.JTextField jtfCpf;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfTelefone;
    // End of variables declaration//GEN-END:variables
}
